name: awesome_custom_dialog
description: "Awesome flutter dialog makes easy to add custom dialogs inside application"
version: 1.0.0
homepage: https://github.com/devamitkumartiwari/awesome_custom_dialog
repository: https://github.com/devamitkumartiwari/awesome_custom_dialog
issue_tracker: https://github.com/devamitkumartiwari/awesome_custom_dialog/issues


environment:
  sdk: '>=3.13.0 <4.0.0'
  flutter: '>=3.29.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:


