name: awesome_custom_dialog
description: "Awesome flutter dialog makes easy to add custom dialogs inside application"
version: 0.0.1
homepage: https://github.com/devamitkumartiwari/awesome_custom_dialog

environment:
  sdk: '>=3.3.4 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:

